### ISSUE TITLE
Harvester should be using GSA certificates to talk to fgdc2iso

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1999]
## User Story

In order to stick to our documented implementation in the SSP, the data.gov team wants the harvester component to communicate with the fgdc2iso component using GSA certificates.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN I am SSH'd into a production harvester host \
  WHEN I grep for `fgdc2iso_service_url` in the `/etc/ckan/production.ini` file \
  THEN I see the URL starts with `https://`
- [ ] GIVEN I am SSH'd into a production harvester host \
  WHEN I look at the Harvester logs \
  THEN I see no certificate error messages for the fgdc type of harvest source

## Background
`fgdc2iso_service` is supposed to run on port `443` using `https` as shown in line below. However, fgdc2iso is running on port 80.

https://github.com/GSA/datagov-deploy/blob/89ec12eac06d3975a490b79b1964d2eb392365db/ansible/roles/software/ckan/catalog/ckan-app/templates/etc_ckan_production.ini.j2#L221

But since the SSL certificates installed on `catalog_ckan_fgdc2iso_host` are self-signed SSL certificates on sandbox, and signed by GSA internal CA on staging/production, during harvesting, catalog harvester is giving `CERTIFICATE_VERIFY_FAILED` as discussed [here](https://github.com/GSA/datagov-deploy/pull/1965#issuecomment-667562671).

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
This change will improve the security of the communication between these components.

## Sketch

- [ ]  Reference the certificates (already installed on each host in /etc/ssl/certs/ca_certificates) in the CKAN virtualenv

**Comment by mogul** [comment]
@FuhuXia was this fixed by the merged PRs?

**Comment by FuhuXia** [comment]
No, the merged PR did not fix it. @adborden  pointed me to an example how we address similar issue in [pycsw](https://github.com/GSA/datagov-deploy-pycsw/blob/9a6f67207ebfd487cf96109bf59c1c91efe46319/templates/supervisor_worker.conf.j2#L9), so instead of passing the environment variable to the python virtualenv, we can do it in supervisord conf, since the harvest fetch process is also managed by supervisord. Will give it a try.

**Comment by FuhuXia** [comment]
Tried different ways to put this `REQUESTS_CA_BUNDLE` environment var into supervisord conf, all failed. Will see what is the easiest way to add this var into Catalog ckan virtual environment.

**Comment by jbrown-xentity** [comment]
Overcome by https://github.com/GSA/datagov-deploy/issues/2917, closing.
