### ISSUE TITLE
CKAN session cookie is not marked Secure

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2138]
who.secure = True in production.ini for Inventory and Catalog, but I'm seeing the cookies not marked as Secure within the browser.

<img width="1243" alt="Screen Shot 2020-09-14 at 5 09 38 PM" src="https://user-images.githubusercontent.com/509703/93150262-77ecbc80-f6ad-11ea-806c-06f8813304a0.png">

## How to reproduce

1. Login to https://inventory.data.gov/user/login
1. Open developer tools (Application tab in Chrome) to view the cookies.

## Expected behavior

Session cookie is marked Secure.

## Actual behavior

Session cookie is not marked Secure.

**Comment by adborden** [comment]
I wonder if this is related to [apache2 listening on HTTP instead of HTTPS](https://github.com/GSA/datagov-deploy/issues/570).

**Comment by FuhuXia** [comment]
It is resolved on CKAN 2.9 while the cookie `auth_tkt` is set secure, the non relevant cookie `ckan` is left unsecure. Details in [the slack discussion](https://gsa-tts.slack.com/archives/C2N85536E/p1629994575001700?thread_ts=1629931152.012400&cid=C2N85536E). 


![image](https://github.com/user-attachments/assets/a3f7a1ea-b0c0-447f-9818-7af380c10f14)

But after ckan 2.10, cookie `auth_tkt` is decommissioned, `ckan` is the only cookie now. We need to secure it.

**Comment by jbrown-xentity** [comment]
I believe [catalog](https://github.com/GSA/catalog.data.gov/pull/1417) will only affect us if login problems persist, so I think that is the safest test. Then we can merge [inventory](https://github.com/GSA/inventory-app/pull/756)

**Comment by jbrown-xentity** [comment]
Inventory and Catalog are both updated, and the cookie is marked as secure. This should be able to be marked as complete.


![Image](https://github.com/user-attachments/assets/161b861a-3018-4538-822f-69bcd7aae1a0)

**Comment by Bagesary** [comment]
Fuhu will do a review and then bags can close

**Comment by FuhuXia** [comment]
Verified `ckan` cookie is secure after the fix.
