### ISSUE TITLE
Dataset resource icons are missing

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#3645]
On [dataset pages](https://catalog-prod-datagov.app.cloud.gov/dataset/navigation-data-for-marine-geophysical-data-collected-between-point-sal-and-refugio-sta-02), some resource icons are strange. It also looks like there are some other styling issues as well.

## How to reproduce

Description of steps to reproduce the issue.

1. Visit a [dataset page](https://catalog-prod-datagov.app.cloud.gov/dataset/navigation-data-for-marine-geophysical-data-collected-between-point-sal-and-refugio-sta-02)

## Expected behavior

Pretty and nice [resource icons](https://catalog.data.gov/dataset/navigation-data-for-marine-geophysical-data-collected-between-point-sal-and-refugio-sta-02): 

![image](https://user-images.githubusercontent.com/91547795/149396940-5c5d29b7-dc48-4595-8f74-6462225b4efb.png)

## Actual behavior

Not nice [resource icons](https://catalog-prod-datagov.app.cloud.gov/dataset/navigation-data-for-marine-geophysical-data-collected-between-point-sal-and-refugio-sta-02):

![image](https://user-images.githubusercontent.com/91547795/149396995-98b46625-3fe8-4266-af55-cf937fb22f7f.png)

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by jbrown-xentity** [comment]
See example here: https://catalog.data.gov/dataset/directional-wave-and-sea-surface-temperature-measurements-collected-in-situ-by-datawell-d-26-4042

**Comment by nickumia-reisys** [comment]
I believe this is resolved.  @GSA/data-gov-team Can someone else make sure I'm not crazy for thinking this is no longer an issue?
![image](https://user-images.githubusercontent.com/85196563/204654406-8d1bfec3-2ced-4722-a48d-107b531ad713.png)

**Comment by FuhuXia** [comment]
Not resolved. See the example in @jbrown-xentity comments, and see [this one](https://catalog.data.gov/dataset/tiger-line-shapefile-2018-nation-u-s-current-american-indian-alaska-native-native-hawaiian-area).  The icon size is not consistent.

**Comment by btylerburton** [comment]
Removing the overrides in datagovtheme allows CKAN core icon to display correctly. @hkdctol do you have reservations with deleting our custom overrides? If not, I'll make this PR production ready.

<img width="888" alt="Screen Shot 2023-04-14 at 11 11 25 AM" src="https://user-images.githubusercontent.com/104455281/232100117-c47437c0-f51c-4c17-b81c-ff78c40866be.png">
<img width="843" alt="Screen Shot 2023-04-14 at 11 11 06 AM" src="https://user-images.githubusercontent.com/104455281/232100125-feb9c78e-5525-4e71-b9bd-35314068b235.png">
<img width="821" alt="Screen Shot 2023-04-14 at 11 10 58 AM" src="https://user-images.githubusercontent.com/104455281/232100131-ba175b29-c624-4d9e-9eca-41721b0c3dc6.png">
