### ISSUE TITLE
Upgrade USWDS to V3

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4460]
## User Story

In order to maintain our dependencies, datagovteam wants to upgrade USWDS to V3 due to a bug with V2 and the SASS library.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN a repo using USWDS
  THEN it shall be upgraded to V3
  AND the site shall remain unchanged.

## Background

Dependency scans flagged SASS for an upgrade but that is blocked by a bug in USWDS V2.

- https://github.com/GSA/resources.data.gov/pull/608
- https://github.com/uswds/uswds/issues/5440

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

Leaving SASS unpatched long term could incur security risks

## Sketch
[uswds migration to v3 doc](https://designsystem.digital.gov/documentation/migration/)
- [ ] Update version of USWDS to V3 in package.json
- [ ] Attempt to compile the CSS/SASS
- Repos to upgrade:
  - [x] https://github.com/GSA/resources.data.gov
  - [x] https://github.com/GSA/datagov-11ty
  - [x] https://github.com/GSA/ckanext-dcat_usmetadata

**Comment by rshewitt** [comment]
datagov-11ty is using [uswds v3](https://github.com/GSA/datagov-11ty/blob/63989c5cb2c172786c96a3281ba3fef0ee476326/package.json#L66)

**Comment by rshewitt** [comment]
- [uswds upgrade branch](https://github.com/GSA/ckanext-dcat_usmetadata/tree/upgrade-uswds).
- need to get the last cypress test to pass. 
- the ckan 2.10 & 2.10.1 tests are failing at requirement installation. [action](https://github.com/GSA/data.gov/blob/main/.github/workflows/ckan-test.yml)

**Comment by rshewitt** [comment]
cypress tests are flaky but they've all passed after re-running them enough times so my updates work. need to get the ckan 2.10 & 20.1.1 test passing now.

**Comment by rshewitt** [comment]
resolved issue with ckan tests by upgrading pip in the requirements

**Comment by btylerburton** [comment]
cypress tests are still failling after 3 tries. i remember this test specifically being super flaky. might be time to rewrite it?

https://github.com/GSA/ckanext-dcat_usmetadata/actions/runs/6896494912/job/18763713494

**Comment by rshewitt** [comment]
i've had to restart that one more than 3 times to get it to work. yeah I think rewriting it would be good

**Comment by rshewitt** [comment]
it passed. https://github.com/GSA/ckanext-dcat_usmetadata/actions/runs/6896494912
